application: writemecn
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /
  script: helloworld.php

- url: /(.+\.php)$
  script: \1

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
